---
clone:
  depth: 1
kind: pipeline
name: IrawansCI
steps:
  - name: Build & Upload
    image: ubuntu:latest
    commands:
      - apt-get update && apt-get install -y bison build-essential bc bison curl libssl-dev git zip python python3 flex cpio libncurses5-dev wget
      - curl https://gitlab.com/dodyirawan85/scripts/raw/master/kernel-dtbo-docker.sh | bash
    environment:
      TELEGRAM_TOKEN:
        from_secret: BOT_API_KEY
      CHAT_ID:
        from_secret: CHAT_ID
      KERNAME:
        from_secret: KERNEL_NAME
      TYPE:
        from_secret: TYPE
      DEFCONFIG: RMX1971_defconfig
      DEVICE: RMX1971
      SUPPORTED: 5 Pro
      FIRMWARE: RealmeUI
